name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to W1
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.W1_HOST }}
          port: ${{ secrets.W1_PORT }}
          username: ${{ secrets.W1_USERNAME }}
          password: ${{ secrets.W1_PASSWORD }}
          script: |
            source ${{secrets.SOURCE_PATH}} &&  cd ${{ secrets.W1_PATH }}
            git pull
            cd backend
            npm install
            touch ./tmp/restart.txt
            cd ../frontend
            npm install
            npm run build
            cp -r dist/* ${{secrets.W1_FE_DEPLOY_PATH}}
            echo "Deployment successful!"
