name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Installing dependencies
        working-directory: ./frontend
        run: |
          yarn install
      - name: Build frontend
        working-directory: ./frontend
        run: yarn run build
      - name: Setup Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.W1_HOST }}
          port: ${{ secrets.W1_PORT }}
          username: ${{ secrets.W1_USERNAME }}
          password: ${{ secrets.W1_PASSWORD }}
          script: |
            cd ${{ secrets.W1_PATH }}/setup
            ./script.sh
            echo "Deployment successful!"
      - name: Upload frontend Build Artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.W1_HOST }}
          port: ${{ secrets.W1_PORT }}
          username: ${{ secrets.W1_USERNAME }}
          password: ${{ secrets.W1_PASSWORD }}
          source: "frontend/dist/*"
          target: "${{ secrets.W1_FE_DEPLOY_PATH }}"
          strip_components: 2
